language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- oraclejdk8
install:
- mvn -s .travis.maven.settings.xml -version -B
script:
- mvn -fae -s .travis.maven.settings.xml -Pitest clean install
notifications:
  email: false
env:
  global:
  - secure: h2UBs+L83eGd8+vTvd4B5sh+ixjp67JB/5Ko/zGAEt6a3hIgrhqyjiXJmaEH3+jzJZKXUcUC6uOuxXHwZ4ODeF+McHViOjqqUGEynJ7AsLXqSr5SSBKZuY/pb69phQnh7Br5w2D+5IFHWEcjrSo/kHDbeZBVAMFRDeGVwpHy2yA=
  - secure: BADgz+otMMO+gUlFNduU/mgFm1dOfv2ZWAYD3nO1nEwu7Y1QVUsqimHdlqntUcinILDVeD33oT27kElERvr7KyjfDEPSDAVUg5Y/5soezg/tBu0zi3iodAP2GynOMohS/Rfm4+3ajWuEe/Y2SYjFXgldMR9qjP+/31FsVtW8Op0=
  - secure: NdAIni80QslWYdLUhkmc4884QklKfzCYiv9GeetwGaWFvacoBGRpQyy/VnccoDUZNRcgHhNdHGwU/PCyO6WaBcwdmEURRdSbxGab9uMP6U0SwuKFebMzvNl6NZHHzWOpFjkvvlfi4rmfLHZtk3KTp4AMVFionaRNWWveqrz9QEkO6h8S+k11KJBeSFg0m+JauiopwbiRBdETsqHlsFFyLOIBhcOxfqtMXTkJ65ad16HxXmeep9rlVQ4uwDJl0vPIMvlyxCIGC1b/cO3VDmVPhS9Arm0WBLTqz33sk3/QpiKTeNMC5KvIdjSFkImGIIU5+f3RjHSaQzQqYywszynB48yBPJATW2z5GlDYoRQeWywe77rqgiSJE/f37Vhtrl2VA2331J+Cs7WzuqYgooJDLZ4F+ZQ9UCiXxZmwGXAtRcJY3AGij5C1bCbiWPArO/xPFajFLuJ8rb583iRB8eTI1h+vcrjaI73KdKXjc9JTP3Ea4PT6AFU/dSXDZUi2vPlxP+JPrAIC8L47kIN2SMvb6rvNRe0acIvUR5Ub/oV69XQ78oMNJy2wWlyAYarP0MPVWHfOZfEdeW1J1kQtYaYnpigHAqMl88m1ybe6oHThZu+hgYBTKcfomv02FAG57L10l0ALAJ0iV5Jt4+MctYBRukZFWDm45RcjSR4TRMiipU0=
  - secure: k1xUoyqMG9sQlJpKhWs68VUla3tK5Lt5fFQbTm3J36o8CrNOxdQdcHvr39KV5LZ7G4Lw7zsUwFIF73tet4ysxeGqFU2BX7PwgvCdmpW0gaTAjZsziiQEVsPeKqBcuySMnWI8NkXyAQs0Jnb9u0ZdnVu6limAUWzr2wR8a+/SNxtja1W5Q9BSJfmD6h+jTeL41TiF1DbBlGdnGfi1x0At7GF2lBk/50zXJWtsAUZWEdy/N6SBbYG4u25cAUWIR2LV4YBeVATLDchDy82RZi0/jurgy6NkkjW7AbYLzYl8WG30aEJN7eBYgHp7U1cxkJHnrRaJT6KW+N56H7y/Zn+WmcCUE5c6uXIOSmZcIIrrQ+LsmNbGo+6CTWAJI2bXi7k2LzyTCLdd1IhoJG2+HkjSZ8lO9JBCuWw1XSEp+E/08+NExTWUhUnU7XU38LcipS/xtMSn86bBM29AjPp8OWxMA09fZKS3XI7ytNwXEfsjq03QQ8b/LNmaPP8c31+CnHj+lF3MviubtUkWz+pmEA+etQHoCKwDr+RO5A7aJmrmScTV9tOBEA3AE7v3/eEY3jAG667Bo+88balpJSqjAOKNyfYcXwTBSO3qHumeag2Wiop6Fm/RMwiKRMUIi0cII9Y4/AjT5mnef5aXAbt9dsvDXZFMZlddptVfJyOSH90fCmc=
after_success:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
   mvn  -s .travis.maven.settings.xml deploy -DskipTests ;
   curl -X GET http://${env.DEPLOYMENT_JENKINS}/job/Build-Hawkular-Image/build?token=${env.DEPLOYMENT_JENKINS_TOKEN} ;
  fi
