language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- oraclejdk8
install:
- mvn -s .travis.maven.settings.xml -version -B
script:
- mvn -fae -s .travis.maven.settings.xml -Pitest clean install
notifications:
  email: false
env:
  global:
  - secure: h2UBs+L83eGd8+vTvd4B5sh+ixjp67JB/5Ko/zGAEt6a3hIgrhqyjiXJmaEH3+jzJZKXUcUC6uOuxXHwZ4ODeF+McHViOjqqUGEynJ7AsLXqSr5SSBKZuY/pb69phQnh7Br5w2D+5IFHWEcjrSo/kHDbeZBVAMFRDeGVwpHy2yA=
  - secure: BADgz+otMMO+gUlFNduU/mgFm1dOfv2ZWAYD3nO1nEwu7Y1QVUsqimHdlqntUcinILDVeD33oT27kElERvr7KyjfDEPSDAVUg5Y/5soezg/tBu0zi3iodAP2GynOMohS/Rfm4+3ajWuEe/Y2SYjFXgldMR9qjP+/31FsVtW8Op0=
  - secure: aTZX1+7nlUSG5uDf7Up/RDijzPKUpWrPSq1QpRV5KmBDxoSr2aGl32gqvu72t9dciv5AhRvFm8/RnWY+HFYJ4RBykHvbh/JXtJVCjHYcO2k6itVZB6k7AducWRDpOy3dQQZXayKMkYlfwVwnx4kgYipacMSbevlBQwAvh/VPvp1jRuYgrEMV5tiD6kAkmQTvNs25uGh+IWLUQspW95WfAWx9EMqC7RkJEotJtekg7FSrzCynN5aeAM0II5liDuHRAqoREECoeOpMwq3/ftkpJMabNFfIlSv0/y4T+b+MPpCi8m1/4I/JHnrSn076BLnvnwwEn07KJCx0F0v/FMU2WIIO/5+qkVEjb/RzGpCHQNMvCA1XK5SG7Z4uHn+ayOzoTacAOQEfB8Rw3Qu69V52/dJJEr76pxqEUBTJQZO7XgiiQYmq6nhT0Gpqt1QIZu+ZNQuJkk1Bez3iBP+EOgzkF4Q3M54i7n9Uq9ZqZTLXkMky11FjRBOMlGNcsS5CWb5MGjiR399mUGJriXOZ6j/vtvnRxdVcEYd3BEUnjh8Nyh3jqOU9bTS6roBquO23wdhd/IlkAomnCq6elwQLfrX4VlGiiwu5NaFHz6CKoTBilT3D+dVXQPLkib+Vium8/rjqHitsGLIvd9ka7EPVdb/X1uSzVLUkJe0LZF2ZoH9J+zI=
  - secure: ABdRpE0vHWM5E6bCbf9+bh60AbRMynmdqZw8fW4mg08LT3xuFU3qqvmwK4Ao51mSZS29ybiy9uqf8NHYXyhOMlMHju9Dwb8FLmfz6+ZTB1QPHJT2YEs2KaNFV4//7kFxCeVdNhNRM7nKCyMjB8W94liCktASkuNjNewvNMOzdxu/79lnmSDT6Ogx1UhTjVR/9p02LwFujTmWfSXnVa5QB5fg88KD8l5ZWnFEplgkwRm9mcirRz5lMJC8LXLWUFLf9TiRcZ0IvHZrwLeaF7JeigNW1kZXlRcrnGCzVmtz7CuVP+/8TSuytj3RsRkPEZgS0U6FeM/z9WXjkbSdpECQn62RHpl4E/6rThai13QFu9xZlFwt2KbDTkv2vyyR1mVMKlTgLYSjpwNkb0MGHf6IwyXxwBs+RJAZPyMAgaVt+wLJbv9aZ7Hqm1Nc0Ikl3QNDPlBBdBRPtUNEkcRgrI/QDAXfyzDyY7fKHxY5gnYX6r3eBGs/gjaFwY0tqjQX11pNgx+FwZZQLGZ8IIHp1QzXEWCGlylKciEjZoTmHWpTUjCl6ALgIcs3EKOVGUmorfVXS3+TBzToLu1z98VcGClMPXyAEQbq5HLQbV1KQ8IPcpZsSWPoPBgcjwgo3bkSCJntAFFgy7DjdfJtbKaNH//zQDIr7YZLRJE44ZzdIFO++oE=
after_success:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
   mvn  -s .travis.maven.settings.xml deploy -DskipTests ;
   #to be removed
   echo ${DEPLOYMENT_JENKINS} ;
   curl -X GET http://${DEPLOYMENT_JENKINS}/job/Build-Hawkular-Image/build?token=${DEPLOYMENT_JENKINS_TOKEN} ;
  fi
