language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- oraclejdk8
install:
- mvn -s .travis.maven.settings.xml -version -B
script:
- mvn -fae -s .travis.maven.settings.xml -Pitest clean install
notifications:
  email: false
env:
  global:
  - secure: h2UBs+L83eGd8+vTvd4B5sh+ixjp67JB/5Ko/zGAEt6a3hIgrhqyjiXJmaEH3+jzJZKXUcUC6uOuxXHwZ4ODeF+McHViOjqqUGEynJ7AsLXqSr5SSBKZuY/pb69phQnh7Br5w2D+5IFHWEcjrSo/kHDbeZBVAMFRDeGVwpHy2yA=
  - secure: BADgz+otMMO+gUlFNduU/mgFm1dOfv2ZWAYD3nO1nEwu7Y1QVUsqimHdlqntUcinILDVeD33oT27kElERvr7KyjfDEPSDAVUg5Y/5soezg/tBu0zi3iodAP2GynOMohS/Rfm4+3ajWuEe/Y2SYjFXgldMR9qjP+/31FsVtW8Op0=
  - secure: TFBDWmwy+odr2o997jTZ357yCXEqbA1VeTmXuaPy5ihYqT9Hx3MsI8XqKRPvUlIYpdqbGMl46Yi9KUz3WVmhjPseAG2hycfP35xECg0+E5tLm/m0bu6q1QHNwIHOEqeukcmi/7FImX3Hak6PaiKBZ7XHGfgeXo5mNqgS8RJglHYBLHtMqZWBOfClQStUXInOkVql/KuvsK8LyUztzf2uAIXDxkxwE1ttJJeICQa5c2079BQX8Zi4cLPK4PBkLxt6AQSqtt3VdpLw1PWx5WoqsfgetarK5DmS+Gwa5zUyI9cSE4sWgldIjQpLvcNk0G7+zpalHUJj13pbQGoVnuN86qcCsbDgMHVgEDnouVAvUBYz1tiVMS/OPMbdoQbJ0XZaMcD4fQ2hI+uLcsniVRNydVgWkssZ8Qd74fDeSxRIDiZitHJR6y+unYJCKkXYmb1H9Vgub/juD6f0yYP+PSA5loLDxhL8gAdwZc7zPyXhmV2dLBHXg1AZ5rhjjlCyBPPPC3rl73G7DWNd9drOZvwPeKxtAhhDsFscH50j4Epji652ZHi5NviQiw6FF5mmRq7o7fGkmdsQaI9nLBBdaK8TJVo4Powox3qz19eNx6cJdIfn/xCeD79Gcb7YCTfn99undNkVhXxOL4QnN88s+I6SQUpBro+rCXmgxW7C0T/mUDY=
  - secure: rhnjhjO5YLOdBvPsktUiLCikv4++UQqjalVFb57HWqtQnxUZZpXeWRAzyNjox+jLdiMAEsN2+NLD57nYFO1UhMC6tHcTLfAFgOcAG8TruKNXrvyuUgypmgJx8T4shq93ARGH3kv6AOyRnsH5CsZ2RNp938A8GlVCnbRdq3vCyeISdYMZirLwgxl1j7TjzuSp4/Lveq1sqtjWG/mr9LHQN4P0M9Z02WPGLFaIcRcg1iyuIiPqCmmbuH3BLYpt6XYclqfNS9Kt2zbEvkb/gCtxjE09mk3CUyj5vPsU0srOrIZELqIgQminRBhXDUwVAutDs6h8NZYFt36DLclco60bWm78599e+597cEGIX/371wtmPniJfLDNyTwHfO0iqfvauAKpJV3ygPUmp49XVtB0swbbZ0K4NY+l+tZkW5pVrTMs2ikY1jtQKeQnF8DO0SNe0dLjC15DHoNYYDoDuU4Siqb+Q3mncusOMvF9B39SYSXbLmLhBwbJ8tj5OprQzM6sEkljXqFRGmUSpHWcEavz6FjUiu4kuY/2dDHp/pPeM2xayhz2TZISQCRg0O6NswW2yCfXpKHSP1AbE8n8Y+D23ifZGE+WTcSfpBbQ2051rjDh1Q8X45g5jeLF6cFPuxhl4LWvZt9lIyIplFJhkmGqLn89WJ1Myoe1U60JBEPrjf0=
after_success:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
   mvn  -s .travis.maven.settings.xml deploy -DskipTests 
   curl "${DEPLOYMENT_JENKINS}"
   curl -X GET http://${DEPLOYMENT_JENKINS}/job/Build-Hawkular-Image/build?token=${DEPLOYMENT_JENKINS_TOKEN} 
  fi
